services:
  app:
    container_name: app
    build: .
    command: ["hypercorn", "-c", "config.toml", "asgi:app"]
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - api_data:/app/data
    depends_on:
      - db
      - celery

  db:
    container_name: db
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery:
    build: .
    env_file:
      - .env
    command: celery -A make_celery worker --loglevel INFO
    volumes:
      - api_data:/app/data
    depends_on:
      - redis
      - db

  redis:
    container_name: redis
    image: redis

volumes:
  postgres_data:
    driver: local
  api_data:
    driver: local