services:
  app:
    container_name: app
    build: .
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      # - api_data:/app/api_data
    depends_on:
      - db
      - celery

  db:
    container_name: db
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  celery:
    container_name: celery
    build: .
    env_file:
      - .env
    command: celery -A make_celery worker --loglevel INFO
    volumes:
      - .:/app
      # - api_data:/app/api_data
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis

volumes:
  postgres_data:
    driver: local
  api_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/api_data
      o: bind